In [ ]:
# !pip install numpy, pandas

In [1]:
import numpy as np

In [5]:
# генерация массива с случайными целочисленными значениями
# одно случайное значение из диапазона от 0 до 10
# (скалярное значение)
np.random.randint(10)

3

In [6]:
# 1-мерный массив со случ целыми значениями
np.random.randint(10, size=5) 

array([1, 8, 7, 3, 2])

In [7]:
np.random.randint(5, 10, size=5) 

array([7, 7, 8, 6, 5])

In [8]:
# 2-мерный массив
np.random.randint(5, 10, size=(3,5)) 

array([[8, 8, 7, 7, 5],
       [5, 6, 5, 6, 5],
       [8, 7, 5, 9, 6]])

- атрибуты 

In [9]:
arr_1 = np.random.randint(10, size=(3,5))
arr_1

array([[5, 0, 3, 5, 4],
       [2, 5, 2, 2, 8],
       [7, 1, 9, 3, 2]])

In [10]:
# мерность массива (кол-во измерений/осей)
arr_1.ndim

2

In [11]:
# форма массива
arr_1.shape

(3, 5)

In [12]:
arr_1.shape[0]

3

In [13]:
# кол-во всех элементов массива
arr_1.size

15

In [16]:
# тип данных массива
# массивы хранятся только однотипные данные
arr_1.dtype

dtype('int32')

In [17]:
np.random.random(5).dtype

dtype('float64')

In [18]:
arr_1.astype("uint8")

array([[5, 0, 3, 5, 4],
       [2, 5, 2, 2, 8],
       [7, 1, 9, 3, 2]], dtype=uint8)

- индексация

In [19]:
arr_2 = np.random.randint(10, size=10)
arr_2

array([6, 7, 6, 8, 4, 0, 2, 0, 4, 2])

In [20]:
# прямая индексация
arr_2[0]

6

In [21]:
# обратная индексация
arr_2[-1]

2

In [22]:
# индексация 2-мерных массивов
arr_3 = np.random.randint(10, size=(3,4))
arr_3

array([[4, 1, 9, 6],
       [9, 4, 1, 3],
       [9, 7, 5, 7]])

In [23]:
# обычный синтаксис
arr_3[1][2]

1

In [24]:
# синтаксис numpy
arr_3[1, 2]

1

- срезы

In [25]:
# 1-мерный массив
arr_2[:5]

array([6, 7, 6, 8, 4])

In [26]:
arr_2[5:]

array([0, 2, 0, 4, 2])

In [27]:
arr_2[::-2]

array([2, 0, 0, 8, 7])

In [28]:
arr_2[-2:-6:-1]

array([4, 0, 2, 0])

In [29]:
# 2-мерный массив
arr_3[1:, :3]

array([[9, 4, 1],
       [9, 7, 5]])

In [30]:
arr_3[0, 1:]

array([1, 9, 6])

In [31]:
arr_3[:2, 1]

array([1, 4])

- представления (views) и копии (copies)

In [33]:
# срез списка создает копию
my_list = [1,2,3,4,5]
sub_list = my_list[2:]
sub_list

[3, 4, 5]

In [34]:
sub_list[0] = 100
sub_list

[100, 4, 5]

In [35]:
my_list

[1, 2, 3, 4, 5]

In [37]:
# срез массива создает представление исходного массива
my_arr = np.array([1,2,3,4,5])
sub_arr = my_arr[2:]
sub_arr

array([3, 4, 5])

In [38]:
sub_arr[0] = 10
sub_arr

array([10,  4,  5])

In [39]:
my_arr

array([ 1,  2, 10,  4,  5])

In [40]:
copy_arr = my_arr[2:].copy()
copy_arr

array([10,  4,  5])

In [42]:
copy_arr[0] = 1000
copy_arr

array([1000,    4,    5])

In [43]:
my_arr

array([ 1,  2, 10,  4,  5])

- изменение формы

In [44]:
# 1-мерный массив (вектор-строка)
arr_4 = np.arange(1, 10)
arr_4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr_4.shape

(9,)

In [46]:
# вектор-строка
# технически это 2-мерный массив
arr_4.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [47]:
arr_5 = np.random.random((2,3))
arr_5

array([[0.33374655, 0.83409765, 0.45935671],
       [0.36803272, 0.32392137, 0.28507051]])

In [48]:
arr_5.reshape((3,2))

array([[0.33374655, 0.83409765],
       [0.45935671, 0.36803272],
       [0.32392137, 0.28507051]])

In [49]:
arr_5.reshape((6,))

array([0.33374655, 0.83409765, 0.45935671, 0.36803272, 0.32392137,
       0.28507051])

In [50]:
arr_5.reshape((6,1))

array([[0.33374655],
       [0.83409765],
       [0.45935671],
       [0.36803272],
       [0.32392137],
       [0.28507051]])

## Операции
- универсальные функции

In [51]:
a = np.arange(5)
b = np.arange(1,6)

print(a)
print(b)

[0 1 2 3 4]
[1 2 3 4 5]


In [52]:
# поэлементное сложение массивов
# "+" - алиас универсальной функции np.add()
a + b

array([1, 3, 5, 7, 9])

In [53]:
np.add(a, b)

array([1, 3, 5, 7, 9])

In [54]:
np.add(10, 20)

30

In [55]:
# поэлементное умножение (произведение Адамара)
a * b

array([ 0,  2,  6, 12, 20])

In [59]:
a

array([0, 1, 2, 3, 4])

In [57]:
# матричное умножение 
c = b.reshape((5,1))
c

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [58]:
np.dot(a, c)

array([40])

In [ ]:
# a[0] * c[0] + a[1] * c[1] + a[2] * c[2] + ...
