In [1]:
import numpy as np

- агрегирование

Агрегирование - вычисление неких сводных показателей.

In [2]:
arr_1 = np.random.random(10)
arr_1

array([0.29996979, 0.92476252, 0.83645514, 0.32420978, 0.62572606,
       0.20631798, 0.28768258, 0.23363832, 0.72256845, 0.3339011 ])

In [3]:
# сумма
# 1d-array
np.sum(arr_1)

4.795231722919232

In [4]:
# 2d-array
np.sum(arr_1.reshape((2,5)))

4.795231722919232

In [21]:
np.sum(arr_1.reshape((2,5)), axis=0)

array([0.50628777, 1.2124451 , 1.07009346, 1.04677823, 0.95962716])

In [ ]:
# минимум
np.min(arr_1)

In [6]:
# максимум
np.max(arr_1)

0.924762522857003

In [7]:
# среднеарифмитическое
np.mean(arr_1)

0.4795231722919232

- сравнения

In [8]:
arr_2 = np.arange(7)
arr_2

array([0, 1, 2, 3, 4, 5, 6])

In [9]:
arr_2 != 2

array([ True,  True, False,  True,  True,  True,  True])

In [10]:
arr_2 == 2

array([False, False,  True, False, False, False, False])

In [11]:
arr_2 > 3

array([False, False, False, False,  True,  True,  True])

In [13]:
np.arange(10).reshape((5,2)) >= 4

array([[False, False],
       [False, False],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [15]:
# общее сравнение
# имеется ли в массиве значения, отвечающие условию
condition = arr_2 < 4
np.any(condition)

True

In [16]:
# все ли значения отвечают условию
np.all(arr_2 < 2)

False

In [17]:
arr_3 = np.arange(10).reshape((5,2))
arr_3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [18]:
np.any(arr_3 > 7, axis=0)

array([ True,  True])

In [19]:
np.any(arr_3 > 7, axis=1)

array([False, False, False, False,  True])

In [20]:
np.all(arr_3 < 5, axis=0)

array([False, False])

- маскирование

In [22]:
arr_4 = np.random.randint(10, size=5)
arr_4

array([5, 6, 9, 7, 5])

In [23]:
# маска - массив с булевыми значениями
c = arr_4 < 6
c

array([ True, False, False, False,  True])

In [24]:
arr_4[c]

array([5, 5])

In [26]:
# Побитовые операторы & = and, | = or
arr_4[(arr_4 > 5) & (arr_4 < 8)]

array([6, 7])

In [27]:
arr_4[arr_4 != 8]

array([5, 6, 9, 7, 5])

- прихотливая индексация (fancy indieces)

In [30]:
arr_5 = np.arange(10, 20)
arr_5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [32]:
# с помощью списка индексов
arr_5[[3,0,5,7]]

array([13, 10, 15, 17])

In [34]:
# с помощью массива индексов
arr_5[np.array([4,1,9,0])]

array([14, 11, 19, 10])

In [35]:
# с помощью прихотливой индексации может менять форму результирующего массива
fi = np.array(
[[3,0,1],
 [1,1,5]]
)
arr_5[fi]

array([[13, 10, 11],
       [11, 11, 15]])